import {defineField, defineType} from 'sanity'

export default defineType({
  name: 'colorSettings',
  title: 'Paramètres de Couleurs',
  type: 'document',
  fieldsets: [
    {name: 'global', title: 'Couleurs Globales'},
    {name: 'buttons', title: 'Couleurs des Boutons'},
    {name: 'navigation', title: 'Navigation & Menu'},
    {name: 'text', title: 'Couleurs du Texte'},
    {name: 'links', title: 'Couleurs des Liens'},
  ],
  fields: [
    // Global Colors
    defineField({
      name: 'primary',
      title: 'Couleur Primaire (HSL)',
      type: 'string',
      description: 'Format: "32 40% 38%" (sans hsl())',
      placeholder: '32 40% 38%',
      fieldset: 'global',
    }),
    defineField({
      name: 'primaryForeground',
      title: 'Texte sur Primaire (HSL)',
      type: 'string',
      description: 'Couleur du texte sur fond primaire',
      placeholder: '0 0% 100%',
      fieldset: 'global',
    }),
    defineField({
      name: 'secondary',
      title: 'Couleur Secondaire (HSL)',
      type: 'string',
      description: 'Format: "220 45% 18%"',
      placeholder: '220 45% 18%',
      fieldset: 'global',
    }),
    defineField({
      name: 'secondaryForeground',
      title: 'Texte sur Secondaire (HSL)',
      type: 'string',
      placeholder: '0 0% 100%',
      fieldset: 'global',
    }),
    defineField({
      name: 'tertiary',
      title: 'Couleur Tertiaire (HSL)',
      type: 'string',
      description: 'Format: "340 35% 28%"',
      placeholder: '340 35% 28%',
      fieldset: 'global',
    }),
    defineField({
      name: 'tertiaryForeground',
      title: 'Texte sur Tertiaire (HSL)',
      type: 'string',
      placeholder: '0 0% 100%',
      fieldset: 'global',
    }),
    defineField({
      name: 'success',
      title: 'Couleur Succès (HSL)',
      type: 'string',
      description: 'Format: "158 60% 22%"',
      placeholder: '158 60% 22%',
      fieldset: 'global',
    }),
    defineField({
      name: 'successForeground',
      title: 'Texte sur Succès (HSL)',
      type: 'string',
      placeholder: '0 0% 100%',
      fieldset: 'global',
    }),
    defineField({
      name: 'accent',
      title: 'Couleur Accent (HSL)',
      type: 'string',
      description: 'Format: "0 0% 20%"',
      placeholder: '0 0% 20%',
      fieldset: 'global',
    }),
    defineField({
      name: 'accentForeground',
      title: 'Texte sur Accent (HSL)',
      type: 'string',
      placeholder: '0 0% 100%',
      fieldset: 'global',
    }),
    defineField({
      name: 'background',
      title: 'Couleur de Fond (HSL)',
      type: 'string',
      description: 'Format: "30 43% 97%"',
      placeholder: '30 43% 97%',
      fieldset: 'global',
    }),
    defineField({
      name: 'foreground',
      title: 'Couleur de Texte Principal (HSL)',
      type: 'string',
      description: 'Format: "214 59% 20%"',
      placeholder: '214 59% 20%',
      fieldset: 'global',
    }),

    // Button Colors
    defineField({
      name: 'buttonPrimary',
      title: 'Bouton Primaire - Fond (HSL)',
      type: 'string',
      description: 'Couleur de fond du bouton "Nous contacter" et autres boutons principaux',
      placeholder: '32 40% 38%',
      fieldset: 'buttons',
    }),
    defineField({
      name: 'buttonPrimaryText',
      title: 'Bouton Primaire - Texte (HSL)',
      type: 'string',
      description: 'Couleur du texte sur le bouton primaire',
      placeholder: '0 0% 100%',
      fieldset: 'buttons',
    }),
    defineField({
      name: 'buttonPrimaryHover',
      title: 'Bouton Primaire - Hover (HSL)',
      type: 'string',
      description: 'Couleur au survol (optionnel, utilise 90% d\'opacité par défaut)',
      placeholder: '32 40% 35%',
      fieldset: 'buttons',
    }),
    defineField({
      name: 'buttonSecondary',
      title: 'Bouton Secondaire - Fond (HSL)',
      type: 'string',
      description: 'Couleur des boutons secondaires',
      placeholder: '220 45% 18%',
      fieldset: 'buttons',
    }),
    defineField({
      name: 'buttonSecondaryText',
      title: 'Bouton Secondaire - Texte (HSL)',
      type: 'string',
      placeholder: '0 0% 100%',
      fieldset: 'buttons',
    }),
    defineField({
      name: 'buttonCTA',
      title: 'Bouton CTA - Fond (HSL)',
      type: 'string',
      description: 'Couleur des boutons d\'appel à l\'action (ex: "Book a Meeting")',
      placeholder: '32 40% 38%',
      fieldset: 'buttons',
    }),
    defineField({
      name: 'buttonCTAText',
      title: 'Bouton CTA - Texte (HSL)',
      type: 'string',
      placeholder: '0 0% 100%',
      fieldset: 'buttons',
    }),

    // Navigation Colors
    defineField({
      name: 'navBackground',
      title: 'Navigation - Fond (HSL)',
      type: 'string',
      description: 'Couleur de fond de la barre de navigation',
      placeholder: '30 43% 97%',
      fieldset: 'navigation',
    }),
    defineField({
      name: 'navText',
      title: 'Navigation - Texte (HSL)',
      type: 'string',
      description: 'Couleur du texte dans la navigation',
      placeholder: '214 59% 20%',
      fieldset: 'navigation',
    }),
    defineField({
      name: 'navTextHover',
      title: 'Navigation - Texte Hover (HSL)',
      type: 'string',
      description: 'Couleur du texte au survol dans la navigation',
      placeholder: '32 40% 38%',
      fieldset: 'navigation',
    }),
    defineField({
      name: 'navButton',
      title: 'Bouton Navigation (ex: "Nous contacter") - Fond (HSL)',
      type: 'string',
      description: 'Couleur du bouton dans la navigation (ex: "Nous contacter")',
      placeholder: '32 40% 38%',
      fieldset: 'navigation',
    }),
    defineField({
      name: 'navButtonText',
      title: 'Bouton Navigation - Texte (HSL)',
      type: 'string',
      description: 'Couleur du texte du bouton navigation',
      placeholder: '0 0% 100%',
      fieldset: 'navigation',
    }),

    // Text Colors
    defineField({
      name: 'textHeading',
      title: 'Titres - Couleur (HSL)',
      type: 'string',
      description: 'Couleur des titres (h1, h2, h3...)',
      placeholder: '214 59% 20%',
      fieldset: 'text',
    }),
    defineField({
      name: 'textBody',
      title: 'Corps de Texte - Couleur (HSL)',
      type: 'string',
      description: 'Couleur du texte principal',
      placeholder: '214 59% 20%',
      fieldset: 'text',
    }),
    defineField({
      name: 'textMuted',
      title: 'Texte Atténué - Couleur (HSL)',
      type: 'string',
      description: 'Couleur du texte secondaire/atténué',
      placeholder: '214 20% 45%',
      fieldset: 'text',
    }),

    // Link Colors
    defineField({
      name: 'linkColor',
      title: 'Liens - Couleur (HSL)',
      type: 'string',
      description: 'Couleur des liens',
      placeholder: '32 40% 38%',
      fieldset: 'links',
    }),
    defineField({
      name: 'linkHover',
      title: 'Liens - Hover (HSL)',
      type: 'string',
      description: 'Couleur des liens au survol',
      placeholder: '32 40% 35%',
      fieldset: 'links',
    }),
  ],
  preview: {
    prepare() {
      return {
        title: 'Paramètres de Couleurs',
        subtitle: 'Personnalisez les couleurs du site',
      }
    },
  },
})

